# Generated by Django 6.0.6 on 2026-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='KiaCode/media/img', verbose_name='عکس دوره')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', verbose_name='سطح')),
                ('duration_hours', models.IntegerField(verbose_name='مدت زمان (ساعت)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('instructor', models.CharField(max_length=100, verbose_name='مدرس')),
                ('gradient_start', models.CharField(default='#667eea', max_length=20, verbose_name='رنگ شروع گرادینت')),
                ('gradient_end', models.CharField(default='#764ba2', max_length=20, verbose_name='رنگ پایان گرادینت')),
            ],
        ),
    ]
