# Generated by Django 6.0.6 on 2026-06-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
