# Generated by Django 6.0.6 on 2026-06-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Collaboration', 'پیشنهاد همکاری'), ('Course Question', 'سوال درباره دوره\u200cها'), ('Content Suggestion', 'پیشنهاد محتوا'), ('Bug Report', 'گزارش مشکل '), ('Just Saying Hi', 'فقط سلام')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
