# Generated by Django 6.0.6 on 2026-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_f', models.TextField(null=True)),
                ('bio_e', models.TextField(null=True)),
                ('resumes', models.CharField(max_length=100, null=True)),
                ('tool', models.CharField(max_length=100, null=True)),
                ('date_exp', models.DateField(null=True)),
                ('title_exp', models.CharField(max_length=100, null=True)),
                ('place_exp', models.CharField(max_length=100, null=True)),
                ('descripption_exp', models.TextField(null=True)),
                ('date_edu', models.DateField(null=True)),
                ('title_edu', models.CharField(max_length=100, null=True)),
                ('place_edu', models.CharField(max_length=100, null=True)),
                ('descripption_edu', models.TextField(null=True)),
            ],
        ),
    ]
