# Generated by Django 6.0.6 on 2026-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(null=True)),
                ('articles', models.IntegerField(null=True)),
                ('courses', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
