# Generated by Django 6.0.6 on 2026-06-26 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/blog', verbose_name='عکس دوره')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دوره')),
                ('excerpt', models.TextField(verbose_name='توضیحات')),
                ('instructor', models.CharField(max_length=100, verbose_name='مدرس')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاریخ')),
                ('views', models.IntegerField(verbose_name='بازدید')),
                ('tags', models.CharField(blank=True, max_length=50, verbose_name='تگ\u200cها')),
            ],
        ),
    ]
