# Generated by Django 6.0.6 on 2026-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='instructor',
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default=1, max_length=100, verbose_name='نویسنده'),
            preserve_default=False,
        ),
    ]
